{% set name = "furo" %}
{% set version = "2021.2.21b25" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/furo-{{ version }}.tar.gz
  sha256: 80bc9b8d163c03ec6371850068d3098a35b69f4650a37ce66572e3581e677682

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - flit-core >=2,<4
  run:
    - python >=3.6
    - sphinx >3.0
    - beautifulsoup4
    - myst-parser
    - sphinx-inline-tabs


test:
  imports:
    - furo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pradyunsg/furo
  summary: A clean customisable Sphinx documentation theme.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
