{% set name = "furo" %}
{% set version = "2022.6.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/furo-{{ version }}.tar.gz
  sha256: c927848edf3292030d0719ebdab9e16d56f1b91c68562b9be316aa5b843775ab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - STB_USE_SYSTEM_NODE=1

requirements:
  host:
    - flit-core >=2,<4
    - pip
    - python >=3.6
    - sphinx-theme-builder
    - nodejs ==16.13.1
  run:
    - beautifulsoup4
    - myst-parser
    - pygments >=2.7
    - python >=3.6
    - sphinx >=4
    - sphinx-inline-tabs
    - sphinx-basic-ng


test:
  imports:
    # One more reason to dislike type-hints
    # This is a dirty hack because sphinx.application
    # isn't available with a simple `import sphinx`
    - sphinx.application
    - furo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pradyunsg/furo
  summary: A clean customisable Sphinx documentation theme.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asmeurer
    - gforsyth
